Add validations
MTES-MCT/rapportNav pull request #22
Opened 2021-12-22 16:42 UTC by aleckvincent

@SebastienTouze 
J'ai fusionné (rebase) certains commit afin de rendre la review un peu plus lisible ;) 

La PR contient les modifications suivantes : 

- Ajout du composant DateTime
- Ajout de la validation Vue et Symfony avant l'envoie du formulaire

![image](https://user-images.githubusercontent.com/25198637/147125703-a16ae596-bc75-4bbc-9ea2-bdde7b918fbf.png)

![image](https://user-images.githubusercontent.com/25198637/147126119-0de2a347-70a1-4f0a-b100-982655fc82ff.png)

2021-12-23 22:59 UTC, SebastienTouze requested changes
Hello
C'est bon pour moi, à part le commentaire plus haut sur PamRapport. Je te laisse regarder / répondre et on merge. 
Les tests ne passent plus mais le bug semble etre sur le reste du code, je vais essayer de regarder mais on ne va pas bloquer le merge à ce niveau. 
Sur les dépendances du front, tu pourras vérifier que tu as bien les dernières mises à jour, avec un coup de `yarn update` si tu ne l'as pas déjà fait ? 

Merci =)

2021-12-23 22:59 UTC, SebastienTouze commented on src/Entity/PAM/PamRapport.php
> +    private $number;
À quoi correspond cette variable ?

2021-12-24 09:24 UTC, aleckvincent commented on src/Entity/PAM/PamRapport.php
> +    private $number;
C'est le numéro de rapport. Je me rappel plus mais on avait validé l'utilisation de l'id du rapport comme numéro de rapport ?
Si oui, je modifie sur le type de $id en string. ✅ et supprime cette variable.

2021-12-24 09:33 UTC, SebastienTouze approved these changes

2021-12-24 09:33 UTC, merged