[feature] Filtre des rapports en page d'accueil
MTES-MCT/rapportNav pull request #56
Opened 2022-04-22 16:02 UTC by aleckvincent

2022-05-02 13:30 UTC, SebastienTouze commented on src/Repository/PAM/Utils/RapportRepositoryUtils.php
> +            switch(true) {
pourquoi ne pas faire un 
```
switch($periode) {
  case "current": 
...
``` 
?

2022-05-02 13:44 UTC, SebastienTouze requested changes

2022-05-02 13:44 UTC, SebastienTouze commented on src/Repository/PAM/Utils/RapportRepositoryUtils.php
> +                    $start = new \DateTime('-6 months');
Je pense qu'il y a un bug là, on arrive à -6 mois mais cela veut dire que si l'on est le 10 juillet  `$start` vaut le  10 janvier, or on voulait le 1er janvier, sinon on loupe des missions entre le 01 et le 10

2022-05-02 13:44 UTC, SebastienTouze commented on src/Repository/PAM/Utils/RapportRepositoryUtils.php
> +                case strpos($periode, 'annee') === 0:
si c'est à cause de ce cas que tu fais un `switch(true)` (cf commentaire plus haut), ici tu peux mettre un `case(preg_match("annee_[0-9]{4}") ? true : false)` (ou quelque chose du genre)

2022-05-03 08:43 UTC, aleckvincent commented on src/Repository/PAM/Utils/RapportRepositoryUtils.php
> +                case strpos($periode, 'annee') === 0:
Bien vu `case(preg_match("annee_[0-9]{4}") ? true : false)` , mais il retourne `true `/ `false`, il faudrait donc dans ce cas garder le` switch(true)` qui va tester si le case retourne bien `true`

2022-05-03 09:51 UTC, SebastienTouze commented on src/Repository/PAM/Utils/RapportRepositoryUtils.php
> +                case strpos($periode, 'annee') === 0:
OK

2022-05-03 09:51 UTC, SebastienTouze approved these changes

2022-05-03 09:52 UTC, merged